"""initial_schema

Revision ID: d1d4a8a98a38
Revises: 

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd1d4a8a98a38'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('STARTUP', 'FREELANCER', 'ADMIN', name='userrole'), nullable=False),
    sa.Column('github_username', sa.String(length=100), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('freelancer_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('bio', sa.String(length=600), nullable=True),
    sa.Column('experience_level', sa.String(length=60), nullable=True),
    sa.Column('portfolio', sa.String(length=255), nullable=True),
    sa.Column('linkedin', sa.String(length=255), nullable=True),
    sa.Column('resume', sa.String(length=255), nullable=True),
    sa.Column('priority_score', sa.Float(), nullable=False),
    sa.Column('skills', sa.JSON(), nullable=False),
    sa.Column('tech_stack', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('ideas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('original_prompt', sa.Text(), nullable=False),
    sa.Column('refined_prompt', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'APPROVED', 'COMPLETED', name='ideastatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('repositories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('idea_id', sa.Integer(), nullable=False),
    sa.Column('github_repo_id', sa.Integer(), nullable=False),
    sa.Column('owner', sa.String(length=100), nullable=False),
    sa.Column('repo_name', sa.String(length=150), nullable=False),
    sa.Column('url', sa.String(length=300), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('stars', sa.Integer(), nullable=False),
    sa.Column('forks', sa.Integer(), nullable=False),
    sa.Column('language', sa.String(length=50), nullable=True),
    sa.Column('license', sa.String(length=80), nullable=True),
    sa.Column('last_commit', sa.DateTime(), nullable=True),
    sa.Column('is_selected', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['idea_id'], ['ideas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_repositories_github_repo_id'), 'repositories', ['github_repo_id'], unique=False)
    op.create_table('github_repository_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('repository_id', sa.Integer(), nullable=False),
    sa.Column('default_branch', sa.String(length=100), nullable=False),
    sa.Column('latest_commit_sha', sa.String(length=64), nullable=False),
    sa.Column('latest_commit_date', sa.DateTime(), nullable=False),
    sa.Column('stars', sa.Integer(), nullable=False),
    sa.Column('forks', sa.Integer(), nullable=False),
    sa.Column('open_issues', sa.Integer(), nullable=False),
    sa.Column('watchers', sa.Integer(), nullable=False),
    sa.Column('contributors_count', sa.Integer(), nullable=False),
    sa.Column('commits_count', sa.Integer(), nullable=False),
    sa.Column('pull_requests_count', sa.Integer(), nullable=False),
    sa.Column('releases_count', sa.Integer(), nullable=False),
    sa.Column('languages', sa.JSON(), nullable=False),
    sa.Column('topics', sa.JSON(), nullable=False),
    sa.Column('raw_snapshot', sa.JSON(), nullable=False),
    sa.Column('snapshot_version', sa.String(length=64), nullable=False),
    sa.Column('etag', sa.String(length=255), nullable=True),
    sa.Column('fetched_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('repository_id')
    )
    op.create_table('repository_analysis',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('repository_id', sa.Integer(), nullable=False),
    sa.Column('executive_summary', sa.Text(), nullable=False),
    sa.Column('revival_score', sa.Integer(), nullable=False),
    sa.Column('project_health_score', sa.Integer(), nullable=False),
    sa.Column('documentation_score', sa.Integer(), nullable=False),
    sa.Column('technical_debt_score', sa.Integer(), nullable=False),
    sa.Column('trend_score', sa.Integer(), nullable=False),
    sa.Column('safe_to_revive', sa.Boolean(), nullable=False),
    sa.Column('ai_effort_percentage', sa.Float(), nullable=False),
    sa.Column('human_effort_percentage', sa.Float(), nullable=False),
    sa.Column('analysis_metadata', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('repository_id')
    )
    op.create_table('analysis_findings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('analysis_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('ISSUE', 'FEATURE', 'AI_TASK', 'HUMAN_TASK', 'RISK', name='findingtype'), nullable=False),
    sa.Column('severity', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='severity'), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('recommendation', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['analysis_id'], ['repository_analysis.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analysis_findings_analysis_id'), 'analysis_findings', ['analysis_id'], unique=False)
    op.create_table('contributor_matches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('analysis_id', sa.Integer(), nullable=False),
    sa.Column('github_username', sa.String(length=100), nullable=False),
    sa.Column('github_profile', sa.String(length=255), nullable=False),
    sa.Column('avatar_url', sa.String(length=500), nullable=True),
    sa.Column('match_score', sa.Float(), nullable=False),
    sa.Column('recent_activity_score', sa.Float(), nullable=False),
    sa.Column('matched_skills', sa.JSON(), nullable=False),
    sa.Column('recent_repositories', sa.JSON(), nullable=False),
    sa.Column('recommendation_reason', sa.String(length=500), nullable=False),
    sa.ForeignKeyConstraint(['analysis_id'], ['repository_analysis.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('outreach_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('analysis_id', sa.Integer(), nullable=False),
    sa.Column('recipient', sa.String(), nullable=False),
    sa.Column('type', sa.Enum('OWNER', 'CONTRIBUTOR', name='outreachtype'), nullable=False),
    sa.Column('generated_message', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['analysis_id'], ['repository_analysis.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('required_roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('analysis_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=100), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(length=500), nullable=False),
    sa.ForeignKeyConstraint(['analysis_id'], ['repository_analysis.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('required_roles')
    op.drop_table('outreach_messages')
    op.drop_table('contributor_matches')
    op.drop_index(op.f('ix_analysis_findings_analysis_id'), table_name='analysis_findings')
    op.drop_table('analysis_findings')
    op.drop_table('repository_analysis')
    op.drop_table('github_repository_snapshots')
    op.drop_index(op.f('ix_repositories_github_repo_id'), table_name='repositories')
    op.drop_table('repositories')
    op.drop_table('ideas')
    op.drop_table('freelancer_profiles')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
