import { useState } from 'react'
import { useQuery } from '@tanstack/react-query'
import { motion } from 'framer-motion'
import { FileText, Search as SearchIcon, Filter, BarChart3, Calendar } from 'lucide-react'
import { useNavigate } from 'react-router-dom'
import api from '@/lib/api'
import type { AdminIdea } from '@/lib/types'

export default function AdminReports() {
  const navigate = useNavigate()
  const [searchTerm, setSearchTerm] = useState('')
  const [statusFilter, setStatusFilter] = useState<string>('all')

  const { data: ideas, isLoading } = useQuery<AdminIdea[]>({
    queryKey: ['admin', 'ideas'],
    queryFn: () => api.get('/admin/ideas').then((r) => r.data),
  })

  const filteredIdeas = (ideas ?? []).filter((idea: AdminIdea) => {
    if (searchTerm && !idea.original_prompt.toLowerCase().includes(searchTerm.toLowerCase())) return false
    if (statusFilter !== 'all' && idea.status !== statusFilter) return false
    return true
  })

  const getStatusBadge = (status: string) => {
    switch (status) {
      case 'ANALYZED': return 'badge-success'
      case 'APPROVED': return 'badge-primary'
      case 'REFINED': return 'badge-warning'
      default: return 'badge-neutral'
    }
  }

  return (
    <div className="space-y-6">
      <motion.div initial={{ opacity: 0, y: -10 }} animate={{ opacity: 1, y: 0 }}>
        <h1 className="text-2xl font-bold" style={{ color: 'var(--text)' }}>Project Revival Reports</h1>
        <p className="text-sm mt-1" style={{ color: 'var(--text-secondary)' }}>
          Browse all project revival reports generated by startup owners
        </p>
      </motion.div>

      {/* Filters */}
      <div className="card">
        <div className="flex items-center gap-4">
          <div className="flex-1 relative">
            <SearchIcon size={16} className="absolute left-3 top-1/2 -translate-y-1/2" style={{ color: 'var(--text-secondary)' }} />
            <input
              type="text"
              value={searchTerm}
              onChange={(e) => setSearchTerm(e.target.value)}
              className="input-field pl-9"
              placeholder="Search reports by idea name..."
            />
          </div>
          <div className="flex items-center gap-2">
            <Filter size={16} style={{ color: 'var(--text-secondary)' }} />
            <select
              value={statusFilter}
              onChange={(e) => setStatusFilter(e.target.value)}
              className="input-field w-auto"
            >
              <option value="all">All Status</option>
              <option value="ANALYZED">Analyzed</option>
              <option value="REFINED">Refined</option>
              <option value="APPROVED">Approved</option>
              <option value="DRAFT">Draft</option>
            </select>
          </div>
        </div>
      </div>

      {/* Results */}
      {isLoading ? (
        <div className="space-y-4">
          {[1, 2, 3].map((i) => <div key={i} className="h-24 skeleton rounded-2xl" />)}
        </div>
      ) : filteredIdeas.length === 0 ? (
        <div className="card text-center py-12">
          <FileText size={48} className="mx-auto mb-4" style={{ color: 'var(--text-secondary)' }} />
          <h3 className="text-lg font-semibold mb-2">No reports found</h3>
          <p className="text-sm" style={{ color: 'var(--text-secondary)' }}>
            {searchTerm ? 'No reports match your search criteria' : 'No project revival reports have been generated yet'}
          </p>
        </div>
      ) : (
        <div className="space-y-3">
          {filteredIdeas.map((idea: AdminIdea, i: number) => (
            <motion.div
              key={idea.id}
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ delay: i * 0.05 }}
              className="card hover:shadow-md hover:-translate-y-0.5 transition-all duration-200"
            >
              <div className="flex items-start justify-between gap-4">
                <div className="flex-1 min-w-0">
                  <p className="text-sm font-medium mb-2">{idea.original_prompt}</p>
                  <div className="flex items-center gap-3 text-xs" style={{ color: 'var(--text-secondary)' }}>
                    <span className="flex items-center gap-1">
                      <Calendar size={12} />
                      {new Date(idea.created_at).toLocaleDateString()}
                    </span>
                    {idea.has_refined_prompt && (
                      <span className="badge badge-success">Refined</span>
                    )}
                    <span className={`badge ${getStatusBadge(idea.status)}`}>
                      {idea.status}
                    </span>
                    <span>Owner #{idea.owner_id}</span>
                  </div>
                </div>
                <div className="flex items-center gap-2 flex-shrink-0">
                  {idea.status === 'analyzed' && (
                    <span className="text-xs flex items-center gap-1 px-3 py-1.5 rounded-full bg-[#8B5CF6]/10 text-[#8B5CF6]">
                      <BarChart3 size={14} />
                      View Report
                    </span>
                  )}
                </div>
              </div>
            </motion.div>
          ))}
        </div>
      )}
    </div>
  )
}
